### ISSUE TITLE
Error: NextRouter was not mounted. with nextjs 13.3

### ISSUE THREAD

**Issue by EvilaMany** [aralroca/next-translate#1031] opened 2023-04-19 08:41 UTC
**What version of this package are you using?**
2.0.5

**What operating system, Node.js, and npm version?**
Macos, node v16.17.0, npm v8.15.0, yarn 1.22.19

**What happened?**
After I updated project from nextjs 12 to 13.3, appeared the error 
`next-translate - compiled page: / - locale: en - namespaces: auth, validation, errors, modals, ui, shared, landing/meta, landing/shared, landing/exchange - used loader: getStaticProps
Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
    at useRouter (/Users/user/dev/my-proj/node_modules/next/dist/client/router.js:122:15)
    at I18nProvider (/Users/user/dev/my-proj/node_modules/next-translate/lib/cjs/I18nProvider.js:50:37)
    at renderWithHooks (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
error - Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
    at useRouter (/Users/user/dev/my-proj/node_modules/next/dist/client/router.js:122:15)
    at I18nProvider (/Users/user/dev/my-proj/node_modules/next-translate/lib/cjs/I18nProvider.js:50:37)
    at renderWithHooks (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/Users/user/dev/my-proj/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3) {
  digest: undefined
}
`
The project is a monorepo, nextjs app is one of the subapps. I use nextjs 13 transpilePackages option to transpile packages. The app doesnt use nextjs 13 "app" directory, I changed almost nothing after upgrading from nextjs 12 to 13. 

**What did you expect to happen?**
App works

**Observation**
In one another copy of the project after many random manipulations it started working without errors, but I dont know what exactly helped. It appears that the reason lies somewhere in node_modules, but I cant determine where exactly. Copying next-translate and next-translate-plugin folders from working app to non working didnt help. Copying next, react, react-dom, @... didnt help too. Helped only copying whole node_modules folder from working app to not working.

**Comment by aralroca** [comment] 2023-04-19 08:55
Can you create a reproducible repo in order to investigate this error? thanks

**Comment by slevy85** [comment] 2023-06-08 08:56
I have the same issue which happens when I render some components in an API route, which are outside of a "nextJS router context".
Example :

```
// in /pages/api/modal.jsx
import ReactDOMServer from 'react-dom/server'
import I18nProvider from 'next-translate/I18nProvider'
import loadNamespaces from 'next-translate/loadNamespaces'
import MyModal from '../../components/modal'

export default async function modalApi(req,  res) {

const { __namespaces } = await loadNamespaces({
        locale: 'en',
        pathname: '/answers',
      })
      
const html = ReactDOMServer.renderToStaticMarkup(
<I18nProvider lang={locale} namespaces={namespaces}>
   <MyModal />
</I18nProvider>)

}
```

Why would I want to do this ?
Because MyModal is used in pages and in this api route, and it uses `useTranslation` which needs a `I18nProvider`.

It was working with next 12, maybe because `useRouter` outside of a context was "ok", but now in next 13 they decided to throw an error. 
My need would be to be able to use I18nProvider without depending on useRouter, especially when I already give the locale and the namespaces in props.

Glad to help if possible.

**Comment by slevy85** [comment] 2023-06-08 10:04
As a side note, this issue is related to #833

**Comment by aralroca** [comment] 2023-07-20 12:57
@timheerwagen nice to hear it! 😊 then I'm going to close the issue

**Closed by aralroca** 2023-07-20 12:57 UTC

**Comment by tomgreeEn** [comment] 2023-11-28 15:41
It looks like this is an issue again at nextjs 13.5+ (see recent comments on #833 )

Should this issue be reopened ?

**Comment by BretCameron** [comment] 2023-12-11 12:53
I also have this issue attempting to upgrade from Next.js `13.4.19` to `14.0.4` (with next-translate `2.6.2`).

Here is the stack trace:

```
Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
at renderNodeDestructiveImpl (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
at renderElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
at renderIndeterminateComponent (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
at renderNodeDestructive (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
at renderNodeDestructiveImpl (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
at renderElement (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
at renderIndeterminateComponent (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
at renderWithHooks (/home/node/app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
at I18nProvider (/home/node/app/node_modules/next-translate/lib/cjs/I18nProvider.js:50:37)
at useRouter (/home/node/app/node_modules/next/dist/client/router.js:146:15)
```

For now, my workaround is to patch `next-translate` to use `next/compat/router` instead of `next/router` (see [this comment](https://github.com/vercel/next.js/issues/43585#issuecomment-1444568040), for example). 

But I would be interested in a longer-term solution!

**Comment by TheMikeyRoss** [comment] 2024-06-04 20:02
im getting the same issue with next.js v14.2.2 and v14.2.3

**Comment by ssteiger** [comment] 2024-06-08 14:20
me too  "next": "^13.5.6",
