### ISSUE TITLE
examples/with-app-directory not working when upgrade to latest next and reactjs

### ISSUE THREAD

**Issue by chhornponleu** [aralroca/next-translate#993] opened 2023-02-25 15:22 UTC
I cloned the react-translate/examples/with-app-directory and use latest next, react, next-translate. checkout this repo https://github.com/chhornponleu/next-translate-app-dir-demo.

**What happened?**
http://localhost:3000 and http://localhost:3000/en works, while http://localhost:3000/ca, http://localhost:3000/es got error 404.

**What did you expect to happen?**
http://localhost:3000/ca, http://localhost:3000/es should render using the selected locale

**Are you willing to submit a pull request to fix this bug?**
Not sure if I am capable of it.

<img width="362" alt="image" src="https://user-images.githubusercontent.com/14964945/221365252-8c1dc9dd-55fc-4056-ba20-58084defbec3.png">

<img width="550" alt="image" src="https://user-images.githubusercontent.com/14964945/221365237-039a2354-225e-4d78-b50a-1519869c2bd4.png">

**Comment by aralroca** [comment] 2023-02-25 19:25
Looks rare @chhornponleu, I cloned your repo and works fine:

<img width="434" alt="Screenshot 2023-02-25 at 20 19 48" src="https://user-images.githubusercontent.com/13313058/221375711-c7a7f51c-b50b-424e-a56e-6b3fb87af838.png">


The repo example is also in Codesandbox and works fine https://codesandbox.io/p/sandbox/next-translate-app-dir-fw68h2?file=%2Fsrc%2Fapp%2Fpage.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A6%7D%5D

Also, I try it the current next-translate example now locally with Next.js 13.2 and Next-translate-plugin 2.0, and is working fine 😅

Would you provide more info about your SO, node version, etc?

I tried with Node.js v16.19.0 and v18.13.0 and both work fine. Thanks to report it!

**Comment by marcelotk15** [comment] 2023-02-25 21:37
I have the same problem even using the `next-translate-plugin` version 2.0.2:
![image](https://user-images.githubusercontent.com/4443094/221379675-c4083758-8c54-455c-8ffc-f260a18659c3.png)
![image](https://user-images.githubusercontent.com/4443094/221379691-50c9b796-2b4f-4dbd-b859-39ce39de46f9.png)

It only accept if change defaultLocale config for that specific lang.

OS: W11 with WSL1
Node: 16.17.1
NPM: 8.15.0

**Comment by aralroca** [comment] 2023-02-25 22:57
It looks like a middleware problem... I'm going to take a look at the problem. Thanks to report it

**Comment by marcelotk15** [comment] 2023-02-27 18:14
@aralroca @chhornponleu 

With aralroca's report about can be the middleware, I debugged and maybe found the problem: `request.nextUrl.href` is using the lang code in the pathname part but when it is not the defaultLocale it's not using.

![image](https://user-images.githubusercontent.com/4443094/221644201-4053e958-f8e4-4766-8e2d-2f9c5fd649b4.png)
![image](https://user-images.githubusercontent.com/4443094/221644364-16d229cc-6f56-41a4-af0f-c474faa3de3b.png)

Probably the fix, for me is now working fine.

```.tsx
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
import i18n from '../i18n'

export function middleware(request: NextRequest) {
  const locale = request.nextUrl.locale || i18n.defaultLocale

  request.nextUrl.searchParams.set('lang', locale)

 // THIS LINE
  request.nextUrl.href = request.nextUrl.href.replace(`/${locale}`, '')
  
  return NextResponse.rewrite(request.nextUrl)
}
```

![image](https://user-images.githubusercontent.com/4443094/221644910-65c2e2ea-e5db-45aa-a3c2-c36913b27bc0.png)

**Comment by aralroca** [comment] 2023-02-27 19:01
Good catch @marcelotk15  at least is not an issue from the library, a bad middleware implementation in the example!! I'm going to fix it (or feel free to PR)! Thanks!!!

**Comment by aralroca** [comment] 2023-02-28 19:11
I abstracted the app dir logic into [next-load library](https://github.com/aralroca/next-load), if somebody wants to load different things than translations in an easy way 😊 If you try please give some feedback 🙏

The idea is to use next-load package to support also layout, template, loading, etc. Next-load is still in 0.x and is a good way to try and find the best solution + support to integrate next-load in libraries as next-translate before next-load 1.0

Bye the way, I close the issue, already fixed by @marcelotk15 . Thanks

**Closed by aralroca** 2023-02-28 19:11 UTC
Labels: bug

**Comment by fernandojbf** [comment] 2023-05-05 08:48
I believe the 404 in non default languages returned again after 13.4.0. 

I didn't had time to investigate further, but it seems that now the problem is not in the middleware. 
The middleware seems to be working well, removing locale from the href and path and adding it as searchParam. But the the route don't match. 

If you add a new `[lang]/page.tsx` it works. The problem should be in the routing itself.

I will try to investigate further tonight

**Comment by lynn1286** [comment] 2023-05-07 09:51
Hey bro, I'm using the latest version of nextjs, and found that next-translate doesn't work anymore, and 404 appears when I click to access .
codesandbox address ： https://codesandbox.io/p/sandbox/next-translate-app-dir-forked-vp5r4n?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A20%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A11%2C%22startLineNumber%22%3A13%7D%5D

**Comment by aralroca** [comment] 2023-05-18 13:06
@fernandojbf @lynn1286 , the PR solving this is already implemented for https://github.com/aralroca/next-translate-plugin/issues/21 @alvesvin, probably should be fixed in the next release
