### ISSUE TITLE
The value at .i18n has an unexpected property - nextjs.config.js

### ISSUE THREAD

**Issue by kaname-png** [aralroca/next-translate#912] opened 2022-09-17 20:58 UTC
**What version of this package are you using?**
1.5.0

**What operating system, Node.js, and npm version?**
OS: Windows 11
Node: v18.6.0
NPM: 8.13.2
Next: 12.3.0

**What happened?**
When adding options that are next-translate options, then nextjs complains that nextjs options has invalid options.

**What did you expect to happen?**
No errors about invalid options errors, as I am providing them in the i18n.js file and not in the nextjs.config.js options.

```js
// i18n.js

// @ts-check
/** @type {import('next-translate').I18nConfig} */
module.exports = {
	locales: ['es-ES', 'en-US'],
	defaultLocale: 'es-ES',
	pages: {
		'*': ['common', 'layout'],
		'/': ['home']
	},
	loggerEnvironment: 'node',
	defaultNS: 'common'
};

// next.config.js

const nextTranslate = require('next-translate');

/** @type {import('next').NextConfig} */
const nextConfig = {
	reactStrictMode: true,
	swcMinify: true
};

module.exports = nextTranslate(nextConfig);
```

![image](https://user-images.githubusercontent.com/56084970/190876120-3d02a7b3-abc1-4e8f-9e11-4e91deeb9bff.png)

---

One more thing... when you enable type validation in the nextjs.config.js file, typescript complains about importing "const nextTranslate = require('next-translate');" has no callbacks.

```
This expression cannot be called.
  The type "typeof import("e:/Projects/Equipments/Naeko/dashboard/node_modules/next-translate/index")" has no call signatures. ts(2349).
```

![image](https://user-images.githubusercontent.com/56084970/190876155-5f8609a4-bd39-4d27-8b1d-fdae71ecc0b4.png)

---

**Are you willing to submit a pull request to fix this bug?**
I don't know.

**Comment by Dragate** [comment] 2022-09-18 18:29
Duplicate of https://github.com/aralroca/next-translate/issues/887
Fixed in [1.6.0-canary.1](https://github.com/aralroca/next-translate/releases/tag/1.6.0-canary.1)

**Comment by kaname-png** [comment] 2022-09-18 19:33
@Dragate and about the second error?

**Comment by Dragate** [comment] 2022-09-18 20:11
> @Dragate and about the second error?

Seems to me that the type definition file is missing the default export.

**Comment by aralroca** [comment] 2022-09-19 12:48
1.6.0 released with this fix 👍

**Comment by kaname-png** [comment] 2022-09-20 00:12
@aralroca The second error was not fixed.

**Comment by aralroca** [comment] 2022-09-20 07:11
Ok! Feel free to PR in order to add the type

**Closed** 2022-10-03 00:04 UTC
